apiVersion: v1
entries:
  databasement:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/readme: README.md
    apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-17T12:13:37.631763902+01:00"
    description: A Helm chart for Databasement - Database backup management application
    digest: 7d4c54a99adc872b234d032ce4f40b930950e6d01ba024e1211cf872c04ff200
    home: https://david-crty.github.io/databasement/
    keywords:
    - database
    - backup
    - mysql
    - postgresql
    - mariadb
    maintainers:
    - email: david_courtey@yahoo.com
      name: David-Crty
    name: databasement
    sources:
    - https://github.com/David-Crty/databasement
    type: application
    urls:
    - https://david-crty.github.io/databasement/charts/databasement-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-17T12:13:37.631130165+01:00"
