<div>
    <x-select
        :options="$organizations"
        option-value="id"
        option-label="name"
        wire:model="currentOrgId"
        wire:change="switchOrg($event.target.value)"
        icon="o-building-office"
        class="select-sm"
    />
</div>
